## 本課題の目標

* 全体的に、1～3章の内容を理解すること
* NumPy をインポートできること
* 「多次元配列」を書けること
* 配列の操作ができること
* 行列演算ができること

In [8]:
# Step1：NumPyのインポート
import numpy as np


# Step2：多次元配列の定義
a_ndarray = np.arange(6).reshape(3,2)
b_ndarray = np.arange(8).reshape(2,4)
print(a_ndarray)
print(b_ndarray)

# Step3：行列の積の計算をする。
a_b_dot_ndarray = np.dot(a_ndarray, b_ndarray)

# Step4：行列の積の計算結果を表示する。
print(f"行列の積の計算結果：\n{a_b_dot_ndarray}\n")

# Step5：行列の要素の最大値を求めて表示する。
a_b_dot_ndarray_max = np.max(a_b_dot_ndarray)
print(f"行列の要素の最大値：{a_b_dot_ndarray_max}")

[[0 1]
 [2 3]
 [4 5]]
[[0 1 2 3]
 [4 5 6 7]]
行列の積の計算結果：
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]

行列の要素の最大値：47
